### ISSUE TITLE
AfterShip API has become paying? 

### ISSUE THREAD

**Issue by FazCodeFR** [martinkooij/MMM-Parcel#15]
`[2020-11-27 12:27:44.403] [LOG]    Fri Nov 27 2020 12:27:44 GMT+0100 (heure normale d’Europe centrale) Error: You don't have permission to access AfterShip API. Select a plan at https://admin.aftership.com/settings/billing to get access to premium features
    at Function.getApiError (/home/pi/MagicMirror/modules/MMM-Parcel/node_modules/aftership/lib/error/error.js:51:15)
    at Request._callback (/home/pi/MagicMirror/modules/MMM-Parcel/node_modules/aftership/lib/handler.js:64:31)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-Parcel/node_modules/request/request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-Parcel/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Parcel/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12) {
  type: 'Forbidden',
  message: "You don't have permission to access AfterShip API. Select a plan at " +
    'https://admin.aftership.com/settings/billing to get access to premium ' +
    'features',
  code: 403,
  data: {},
  response_body: `{"meta":{"code":403,"message":"You don't have permission to access ` +
    'AfterShip API. Select a plan at ' +
    'https://admin.aftership.com/settings/billing to get access to premium ' +
    'features","type":"Forbidden"},"data":{}}'
}
`

**Comment by martinkooij** [comment]
That is correct. I had to change the code to use **Tracktry.com**. Tracktry is free for now... (We'll see).
Also I cleaned some code. Have fun.

**Comment by xIExodusIx** [comment]
Hi there,
I'm searching for a functional Tracking-App and found your MMM-Parcel. I uesed it for several Month. 
But sadly I can't get it to work anymore. 
The reason is that both (aftership.com and Tracktry.com) are not free anymore. 
Following your Link to Tracktry.com will lead you to trackingmore.com, when you try to make an account, and there I have to pay. 
But I'm an privat person no commercial Shop, I want to track 1 to 15 Packages in a single year, NOT up to 100 a month. 
Is it possible to find any other free parcel tracking partners? Maybe 17Track.com or parcelsapp.com?
It would be nice to get MMM-Parcel work again.
