### ISSUE TITLE
Problem with new installation

### ISSUE THREAD

**Issue by SdeGeata** [martinkooij/MMM-Parcel#30]
Hello;

So I am in the process of upgrading to a R.pi 4 and in doing so, am now installing my favorite modules on the new device. I am however running into issues with this module. It keeps throwing errors. Here's the log:

`0|mm  | [30.09.2021 20:26.15.090] [ERROR] 
0|mm  | App threw an error during load
0|mm  | [30.09.2021 20:26.15.091] [ERROR] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js
0|mm  | require() of ES modules is not supported.
0|mm  | require() of /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js from /home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
0|mm  | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/package.json.
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1169:13)
0|mm  |     at Module.load (internal/modules/cjs/loader.js:992:32)
0|mm  |     at Module._load (internal/modules/cjs/loader.js:885:14)
0|mm  |     at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
0|mm  |     at Module.require (internal/modules/cjs/loader.js:1032:19)
0|mm  |     at require (internal/modules/cjs/helpers.js:72:18)
0|mm  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js:9:18)
0|mm  |     at Module._compile (internal/modules/cjs/loader.js:1152:30)
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
0|mm  |     at Module.load (internal/modules/cjs/loader.js:992:32)
0|mm  | [30.09.2021 20:26.15.092] [ERROR] Whoops! There was an uncaught exception...
0|mm  | [30.09.2021 20:26.15.099] [ERROR] 
0|mm  | Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js
0|mm  | require() of ES modules is not supported.
0|mm  | require() of /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/src/index.js from /home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
0|mm  | Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/pi/MagicMirror/modules/MMM-Parcel/node_modules/node-fetch/package.json.
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1169:13)
0|mm  |     at Module.load (internal/modules/cjs/loader.js:992:32)
0|mm  |     at Module._load (internal/modules/cjs/loader.js:885:14)
0|mm  |     at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
0|mm  |     at Module.require (internal/modules/cjs/loader.js:1032:19)
0|mm  |     at require (internal/modules/cjs/helpers.js:72:18)
0|mm  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Parcel/node_helper.js:9:18)
0|mm  |     at Module._compile (internal/modules/cjs/loader.js:1152:30)
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
0|mm  |     at Module.load (internal/modules/cjs/loader.js:992:32) {
0|mm  |   code: 'ERR_REQUIRE_ESM'
0|mm  | }
0|mm  | [30.09.2021 20:26.15.100] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm  | [30.09.2021 20:26.15.101] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues`

How can I fix this?

**Comment by SdeGeata** [comment]
@martinkooij : Any idea how i can fix this? It worked before this.

**Comment by SdeGeata** [comment]
Fixed! [https://github.com/MichMich/MagicMirror/issues/2684](url)
